ARG BASE_IMAGE="debian:trixie"
FROM debian:trixie
ARG DEBIAN_FRONTEND=noninteractive

ARG DEBIAN_VERSION=trixie

RUN apt update && \
    apt install -y \
    wget \
    nano \
    curl \
    gnupg \
    cmake \
    ninja-build \
    python3 \
    build-essential \
    zlib1g-dev \
    vim \
    ca-certificates \
    apt-utils \
    && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

# Install LLVM librust-llvm-sys
ARG LLVM_VERSION="22.1.2"
RUN curl -LO https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${LLVM_VERSION}.tar.gz && \
    tar -xzf llvmorg-${LLVM_VERSION}.tar.gz && \
    cd llvm-project-llvmorg-${LLVM_VERSION} && \
    mkdir build && \
    cd build && \
    cmake -G Ninja ../llvm \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local/llvm-22 \
      -DLLVM_ENABLE_PROJECTS="" \
      -DLLVM_TARGETS_TO_BUILD="AArch64" \
      -DLLVM_BUILD_TOOLS=ON \
      -DLLVM_INCLUDE_TESTS=OFF \
      -DLLVM_INCLUDE_EXAMPLES=OFF \
      -DLLVM_INCLUDE_BENCHMARKS=OFF \
      -DLLVM_ENABLE_BINDINGS=OFF && \
    ninja -j$(nproc) && \
    ninja install;
ENV LLVM_SYS_221_PREFIX="/usr/local/llvm-22"

ARG ARCH
RUN ARCH=$(dpkg --print-architecture) \
&& if [ "$ARCH" = "amd64" ]; then \
    echo "deb $PVE_APT/proxmox/debian/pve ${DEBIAN_VERSION} pve-no-subscription" >> /etc/apt/sources.list;  \
    echo "deb $PVE_APT/proxmox/debian/devel ${DEBIAN_VERSION} main" >> /etc/apt/sources.list; \
    curl -l -o /etc/apt/trusted.gpg.d/proxmox-release-${DEBIAN_VERSION}.gpg $PVE_APT/proxmox/debian/proxmox-release-bookworm.gpg; \
fi

RUN apt update && \
    apt -y install \
    build-* \
    devscripts \
    cargo \
    dh-cargo \
    devscripts \
    rsync \
    debcargo \
    pkg-config \
    debhelper \
    git \
    bison \
    dwarves \
    flex \
    meson \
    equivs \
    golang-go && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

# Set up apt preferences
COPY etc/apt/preferences.d/exclude-librust /etc/apt/preferences.d/

# Install build requirements
RUN apt update && \
    apt -y install \
    libgit2-dev \
    # librust-cmake \
    cmake \
    # librust-pulldown-cmark \
    help2man \
    # librust-zstd \
    libzstd-dev \
    # librust-pam-sys \
    libpam-dev \
    # lilbrust-openssl-sys \
    libssl-dev \
    # librust-clang-sys \
    clang \
    libclang-19-dev \
    libclang-dev \
    llvm \
    llvm-runtime \
    # librust-proxmox \
    # librust-ureq-dev \
    # ceph-18 build dependencies \
    libopentracing-dev \
    libthrift-dev \
    liblttng-ust-dev \
    default-jdk \
    # pve-common build dependencies \
    libanyevent-perl \
    libdevel-cycle-perl \
    libfilesys-df-perl \
    liblinux-inotify2-perl \
    libnet-ip-perl \
    libtest-mockmodule-perl \
    # proxmox-perl-rs build dependencies \
    # librust-anyhow-dev \
    # librust-base32-dev \
    # librust-base64-dev \
    # librust-hex-dev \
    # librust-http-dev \
    # librust-http-0.2-dev \
    # pve-xtermjs \
    # librust-form-urlencoded-dev \
    # librust-mio-dev \
    # librust-nix-dev \
    # librust-pico-args-dev \
    # pve-doc \
    asciidoc-dblatex \
    asciidoc-base \
    imagemagick-7.q16 \
    librsvg2-bin \
    source-highlight \
    && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

RUN apt update && \
    apt-get -y --no-install-recommends install proxmox-ve || echo ok \
    && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

# Install rust
ARG RUST_VERSION="1.94.0"
RUN curl -L "https://static.rust-lang.org/dist/rust-${RUST_VERSION}-$(arch)-unknown-linux-gnu.tar.xz" -o rust.tar.xz && \
    mkdir -p ./rust/ && \
    tar -xf rust.tar.xz -C ./rust/ --strip-components=1 && \
    /bin/bash -c "./rust/install.sh" && \
    /usr/local/bin/cargo install debcargo && \
    rm -fr rust*;
ENV PATH=/root/.cargo/bin/:${PATH}

RUN rm -f /var/lib/dpkg/info/pve-manager.postinst && \
    rm -f /var/lib/dpkg/info/proxmox-ve.postinst && \
    dpkg --configure -a

ADD ./start.sh /
CMD ["/bin/bash"]
