ARG BASE_IMAGE="debian:trixie"
FROM ${BASE_IMAGE}
ARG DEBIAN_FRONTEND=noninteractive

ARG DEBIAN_VERSION=trixie

RUN apt update && \
    apt install -y \
    wget \
    nano \
    curl \
    gnupg \
    cmake \
    ninja-build \
    python3 \
    build-essential \
    zlib1g-dev \
    vim \
    ca-certificates \
    apt-utils \
    && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

# Install LLVM librust-llvm-sys
ARG LLVM_VERSION="22.1.7"
RUN curl -LO https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-${LLVM_VERSION}.tar.gz && \
    tar -xzf llvmorg-${LLVM_VERSION}.tar.gz && \
    cd llvm-project-llvmorg-${LLVM_VERSION} && \
    mkdir build && \
    cd build && \
    cmake -G Ninja ../llvm \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/usr/local/llvm-22 \
      -DLLVM_ENABLE_PROJECTS="" \
      -DLLVM_TARGETS_TO_BUILD="AArch64" \
      -DLLVM_BUILD_TOOLS=ON \
      -DLLVM_INCLUDE_TESTS=OFF \
      -DLLVM_INCLUDE_EXAMPLES=OFF \
      -DLLVM_INCLUDE_BENCHMARKS=OFF \
      -DLLVM_ENABLE_BINDINGS=OFF && \
    ninja -j$(nproc) && \
    ninja install;
ENV LLVM_SYS_221_PREFIX="/usr/local/llvm-22"

RUN apt update && \
    apt -y install \
    build-* \
    devscripts \
    cargo \
    dh-cargo \
    devscripts \
    rsync \
    debcargo \
    pkg-config \
    debhelper \
    git \
    bison \
    dwarves \
    flex \
    meson \
    equivs \
    golang-go && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

# Set up apt preferences
COPY etc/apt/preferences.d/exclude-librust /etc/apt/preferences.d/

# Install build requirements for Proxmox
RUN apt update && \
    apt -y install \
    libgit2-dev \
    # proxmox-i18n \
    liblocale-po-perl \
    # ceph-18 build dependencies \
    libopentracing-dev \
    libthrift-dev \
    liblttng-ust-dev \
    default-jdk \
    # proxmox-offline-mirror build dependencies \
    latexmk \
    fonts-open-sans \
    # pve-common build dependencies \
    libanyevent-perl \
    libdevel-cycle-perl \
    libfilesys-df-perl \
    liblinux-inotify2-perl \
    libnet-ip-perl \
    libtest-mockmodule-perl \
    # pve-doc \
    asciidoc-dblatex \
    asciidoc-base \
    imagemagick-7.q16 \
    librsvg2-bin \
    source-highlight \
    && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

# Install rust
ARG RUST_VERSION="1.96.0"
RUN curl -L "https://static.rust-lang.org/dist/rust-${RUST_VERSION}-$(arch)-unknown-linux-gnu.tar.xz" -o rust.tar.xz && \
    mkdir -p ./rust/ && \
    tar -xf rust.tar.xz -C ./rust/ --strip-components=1 && \
    /bin/bash -c "./rust/install.sh" && \
    rm -fr rust*;
ENV PATH=/root/.cargo/bin/:${PATH}

# Install build requirements for librust
RUN apt update && \
    apt -y install \
    # librust-cmake \
    cmake \
    # librust-pulldown-cmark \
    help2man \
    # librust-zstd \
    libzstd-dev \
    # librust-pam-sys \
    libpam-dev \
    # lilbrust-openssl-sys \
    libssl-dev \
    # librust-clang-sys \
    clang \
    libclang-19-dev \
    libclang-dev \
    llvm \
    llvm-runtime \
    # librust-brotli \
    brotli \
    # librust-tower-http \
    python3-inflate64 \
    # librust-bzip2-sys \
    # libbz2-dev \
    # librust-nettle-sys \
    nettle-dev \
    # librust-apt-native \
    libapt-pkg-dev \
    # librust-proxmox-sys \
    libacl1-dev \
    # librust-proxmox-systemd \
    libsystemd-dev \
    # librust-rrd-sys \
    librrd-dev \
    && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

ADD ./start.sh /
CMD ["/bin/bash"]
