ARG BASE_IMAGE="debian:trixie"
FROM debian:trixie
ARG DEBIAN_FRONTEND=noninteractive

ARG DEBIAN_VERSION=trixie
ARG DEBIAN_APT=http://mirrors.ustc.edu.cn
RUN rm /etc/apt/sources.list.d/*  \
&& echo "deb $DEBIAN_APT/debian  ${DEBIAN_VERSION} main contrib non-free non-free-firmware" >/etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian  ${DEBIAN_VERSION}-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian  ${DEBIAN_VERSION}-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian-security  ${DEBIAN_VERSION}-security main contrib non-free non-free-firmware " >> /etc/apt/sources.list 

RUN apt update && apt install -y wget nano curl gnupg  ca-certificates apt-utils

ARG ARCH
RUN ARCH=$(dpkg --print-architecture) \
&& if [ "$ARCH" = "amd64" ]; then \
    echo "deb $PVE_APT/proxmox/debian/pve ${DEBIAN_VERSION} pve-no-subscription" >> /etc/apt/sources.list;  \
    echo "deb $PVE_APT/proxmox/debian/devel ${DEBIAN_VERSION} main" >> /etc/apt/sources.list; \
    curl -l -o /etc/apt/trusted.gpg.d/proxmox-release-${DEBIAN_VERSION}.gpg $PVE_APT/proxmox/debian/proxmox-release-bookworm.gpg; \
fi

RUN apt update && \
    apt -y install \
    build-* \
    git \
    devscripts \
    cargo \
    dh-cargo \
    devscripts \
    rsync \
    debcargo \
    pkg-config \
    debhelper \
    git \
    bison \
    dwarves \
    flex \
    meson \
    equivs;

RUN apt update && \
    apt-get -y --no-install-recommends install proxmox-ve || echo ok

RUN rm -f /var/lib/dpkg/info/pve-manager.postinst && \
    dpkg --configure -a

ADD ./start.sh /

CMD ["bash","/start.sh"]
