ARG BASE_IMAGE="debian:trixie"
FROM debian:trixie
ARG DEBIAN_FRONTEND=noninteractive

ARG DEBIAN_VERSION=trixie
ARG DEBIAN_APT=http://mirrors.ustc.edu.cn
RUN rm /etc/apt/sources.list.d/*  \
&& echo "deb $DEBIAN_APT/debian  ${DEBIAN_VERSION} main contrib non-free non-free-firmware" >/etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian  ${DEBIAN_VERSION}-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian  ${DEBIAN_VERSION}-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian-debug ${DEBIAN_VERSION}-debug main" >> /etc/apt/sources.list \
&& echo "deb $DEBIAN_APT/debian-security  ${DEBIAN_VERSION}-security main contrib non-free non-free-firmware " >> /etc/apt/sources.list 

RUN apt update && apt install -y wget nano curl gnupg  ca-certificates apt-utils

ARG ARCH
RUN ARCH=$(dpkg --print-architecture) \
&& if [ "$ARCH" = "amd64" ]; then \
    echo "deb $PVE_APT/proxmox/debian/pve ${DEBIAN_VERSION} pve-no-subscription" >> /etc/apt/sources.list;  \
    echo "deb $PVE_APT/proxmox/debian/devel ${DEBIAN_VERSION} main" >> /etc/apt/sources.list; \
    curl -l -o /etc/apt/trusted.gpg.d/proxmox-release-${DEBIAN_VERSION}.gpg $PVE_APT/proxmox/debian/proxmox-release-bookworm.gpg; \
fi

RUN apt update && \
    apt -y install \
    build-* \
    devscripts \
    cargo \
    dh-cargo \
    devscripts \
    rsync \
    debcargo \
    pkg-config \
    debhelper \
    git \
    bison \
    dwarves \
    flex \
    meson \
    equivs && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

RUN apt update && \
    apt -y install \
    libgit2-dev \
    # librust-proxmox \
    librust-ureq-dev \
    # ceph-18 build dependencies \
    libopentracing-dev \
    libthrift-dev \
    liblttng-ust-dev \
    default-jdk \
    # pve-common build dependencies \
    libanyevent-perl \
    libdevel-cycle-perl \
    libfilesys-df-perl \
    liblinux-inotify2-perl \
    libnet-ip-perl \
    libtest-mockmodule-perl \
    # proxmox-perl-rs build dependencies \
    librust-anyhow-dev \
    librust-base32-dev \
    librust-base64-dev \
    librust-hex-dev \
    librust-http-dev \
    librust-http-0.2-dev \
    # pve-xtermjs \
    librust-form-urlencoded-dev \
    librust-mio-dev \
    librust-nix-dev \
    librust-pico-args-dev \
    # pve-doc \
    asciidoc-dblatex \
    asciidoc-base \
    imagemagick-7.q16 \
    librsvg2-bin \
    source-highlight \
    && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

RUN apt update && \
    apt-get -y --no-install-recommends install proxmox-ve || echo ok \
    && \
    apt autoremove --purge -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*;

# Install rust
ARG RUST_VERSION="1.94.0"
RUN curl -L "https://static.rust-lang.org/dist/rust-${RUST_VERSION}-$(arch)-unknown-linux-gnu.tar.xz" -o rust.tar.xz && \
    mkdir -p ./rust/ && \
    tar -xf rust.tar.xz -C ./rust/ --strip-components=1 && \
    /bin/bash -c "./rust/install.sh";

RUN rm -f /var/lib/dpkg/info/pve-manager.postinst && \
    rm -f /var/lib/dpkg/info/proxmox-ve.postinst && \
    dpkg --configure -a

ADD ./start.sh /
CMD ["/bin/bash"]
