#!/bin/bash

set -e

SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)
PKGNAME=$(basename $SCRIPT_DIR)

echo "This is $PKGNAME build scripts"

. ../common.sh

cd $SCRIPT_DIR/$PKGNAME

arch=`arch`
if [[ "$arch" == "loongarch64" || "$arch" == "aarch64" ]];then
  for i in `cat $SCRIPT_DIR/series`; do
    patch --forward -p1 < ../$i || true
  done
fi

RUST_LIBS=(
    # "shlex:shlex"
    # "unicode-ident:unicode-ident"
    # "proc-macro2:proc-macro2"
    # "quote:quote"
    # "syn:syn"
    # "serde-derive:serde_derive"
    # "serde-core:serde_core"
    # "serde:serde"
    # "serde-bytes:serde_bytes"
    # "serde-plain:serde_plain"
    # "bit-vec:bit-vec"
    # "bit-set:bit-set"
    # "rustc-std-workspace-core:rustc-std-workspace-core"
    # "cfg-if:cfg-if"
    # "libc:libc"
    # "errno:errno"
    # "r-efi:r-efi"
    # "anyhow:anyhow"
    # "heck:heck"
    # "either:either"
    # "crossbeam-utils:crossbeam-utils"
    # "crossbeam-epoch:crossbeam-epoch"
    # "crossbeam-deque:crossbeam-deque"
    # "critical-section:critical-section"
    # "derive-arbitrary:derive_arbitrary"
    # "arbitrary:arbitrary"
    # "smallvec:smallvec"
    # "parking-lot-core:parking_lot_core"
    # "portable-atomic:portable-atomic"
    # "once-cell:once_cell"
    # "wasm-bindgen-shared:wasm-bindgen-shared"
    # "allocator-api2:allocator-api2"
    # "bumpalo:bumpalo"
    # "wasm-bindgen-macro-support:wasm-bindgen-macro-support"
    # "wasm-bindgen-macro:wasm-bindgen-macro"
    # "rustversion:rustversion"
    # "no-panic:no-panic"
    # "itoa:itoa"
    # "jobserver:jobserver"
    # "cc:cc"
    # "compiler-builtins:compiler_builtins"
    # "sval-derive-macros:sval_derive_macros"
    # "sval:sval"
    # "sval-ref:sval_ref"
    # "sval-buffer:sval_buffer"
    # "typeid:typeid"
    # "erased-serde:erased-serde"
    # "serde-fmt:serde_fmt"
    # "sval-dynamic:sval_dynamic"
    # "ryu:ryu"
    # "sval-fmt:sval_fmt"
    # "sval-nested:sval_nested"
    # "sval-serde:sval_serde"
    # "sval-json:sval_json"
    # "sval-test:sval_test"
    # "value-bag-sval2:value-bag-sval2"
    # "memchr:memchr"
    # "foldhash:foldhash"
    # "prettyplease:prettyplease"
    # "leb128fmt:leb128fmt"
    # "rustc-std-workspace-std:rustc-std-workspace-std"
    # "unicode-width:unicode-width"
    # "bytemuck-derive:bytemuck_derive"
    # "bytemuck:bytemuck"
    # "bitflags:bitflags"
    # "semver:semver"
    # "wasmparser:wasmparser"
    # "wasm-encoder:wasm-encoder"
    # "fallible-iterator:fallible-iterator"
    # "fnv:fnv"
    # "stable-deref-trait:stable_deref_trait"
    # "linux-raw-sys:linux-raw-sys"
    # "rustc-std-workspace-alloc:rustc-std-workspace-alloc"
    # "equivalent:equivalent"
    # "hashbrown:hashbrown"
    # "gimli:gimli"
    # "wast:wast"
    # "wat:wat"
    # "rayon-core:rayon-core"
    # "rayon:rayon"
    # "id-arena:id-arena"
    # "indexmap:indexmap"
    # "serde-json:serde_json"
    # "serde-test:serde_test"
    # "serde-buf:serde_buf"
    # "serde-buf:serde_buf"
    # "value-bag-serde1:value-bag-serde1"
    # "value-bag:value-bag"
    # "log:log"
    # "unicode-xid:unicode-xid"
    # "wit-parser:wit-parser"
    # "clap-lex:clap_lex"
    "pulldown-cmark:pulldown-cmark"
    "clap-derive:clap_derive"
    "anstyle:anstyle"
    "utf8parse:utf8parse"
    "zeroize-derive:zeroize_derive"
    "zeroize:zeroize"
    "arrayvec:arrayvec"
    "anstyle-parse:anstyle-parse"
    "anstyle-query:anstyle-query"
    "colorchoice:colorchoice"
    "is-terminal-polyfill:is_terminal_polyfill"
    "anstream:anstream"
    "strsim:strsim"
    "unicase:unicase"
    "clap-builder:clap_builder"
    "clap:clap"
    "wit-bindgen-core:wit-bindgen-core"
    "wit-bindgen-rust-macro:wit-bindgen-rust-macro"
    "wit-bindgen:wit-bindgen"
    "wasip2:wasip2"
    "getrandom:getrandom"
    "ahash:ahash"
    "wasm-bindgen:wasm-bindgen"
    "js-sys:js-sys"
    "wasm-sync:wasm_sync"
    "serde-test:serde_test"
    "rand-core:rand_core"
    "rand-xorshift:rand_xorshift"
    "rand-chacha:rand_chacha"
    "rand:rand"
    "openssl:openssl"
    "openssl-probe:openssl-probe"
    "url:url"
    "futures-core:futures-core"
    "futures-sink:futures-sink"
    "futures-channel:futures-channel"
    "futures-task:futures-task"
    "futures-macro:futures-macro"
    "pin-project-lite:pin-project-lite"
    "slab:slab"
    "futures-io:futures-io"
    "futures-util:futures-util"
    "num-cpus:num_cpus"
    "futures-executor:futures-executor"
    "futures:futures"
    "http-body:http-body"
    "http-body-util:http-body-util"
    "parking-lot:parking_lot"
    "tracing-attributes:tracing-attributes"
    "valuable-derive:valuable-derive"
    "valuable:valuable"
    "tracing-core:tracing-core"
    "tracing:tracing"
    "socket2:socket2"
    "tokio-macros:tokio-macros"
    "signal-hook-registry:signal-hook-registry"
    "tokio:tokio"
    "httparse:httparse"
    "httpdate:httpdate"
    "try-lock:try-lock"
    "want:want"
    "atomic-waker:atomic-waker"
    "tokio-util:tokio-util"
    "h2:h2"
    "hyper:hyper"
    "ipnet:ipnet"
    "tower-service:tower-service"
    "hyper-util:hyper-util"
    "zstd-sys:zstd-sys"
    "zstd-safe:zstd-safe"
    "zstd:zstd"
    "const-format-proc-macros:const_format_proc_macros"
    "const-format:const_format"
    "env-logger:env_logger"
    "xattr:xattr"
    "filetime:filetime"
    "tar:tar"
    "winapi-util:winapi-util"
    "winapi:winapi"
    "same-file:same-file"
    "walkdir:walkdir"
    "sync-wrapper:sync_wrapper"
    "tokio-openssl:tokio-openssl"
    "tokio-stream:tokio-stream"
    "smawk:smawk"
    "unicode-linebreak:unicode-linebreak"
    "textwrap:textwrap"
    "nu-ansi-term:nu-ansi-term"
    "alloca:alloca"
    "criterion-plot:criterion-plot"
    "criterion:criterion"
    "spin:spin"
    "lazy-static:lazy_static"
    "sharded-slab:sharded-slab"
    "thread-local:thread_local"
    "lru:lru"
    "tracing-log:tracing-log"
    "pure-rust-locales:pure-rust-locales"
    "iana-time-zone:iana-time-zone"
    "chrono:chrono"
    "matchers:matchers"
    "valuable-serde:valuable-serde"
    "tracing-serde:tracing-serde"
    "tracing-subscriber:tracing-subscriber"
    "tracing-journald:tracing-journald"
    "thiserror-impl-1:thiserror-impl 1"
    "thiserror-impl:thiserror-impl"
    "thiserror-1:thiserror 1"
    "ucd-trie:ucd-trie"
    "pest:pest"
    "pest-meta:pest_meta"
    "pest-generator:pest_generator"
    "pest-derive:pest_derive"
    "tempfile:tempfile"
    "rustix:rustix"
    "rusty-fork:rusty-fork"
    "proptest:proptest"
    "smartstring:smartstring"
    "rhai-codegen:rhai_codegen"
    "rhai:rhai"
    "rust-embed:rust-embed"
    "handlebars:handlebars"
    "serde-with:serde_with"
    "pam:pam"
    "regex:regex"
    "base64urlsafedata:base64urlsafedata"
    "openssl-macros:openssl-macros"
    "openssl-sys:openssl-sys"
    "compact-jwt:compact_jwt"
    "der-parser:der-parser"
    "serde-cbor:serde_cbor"
    "serde-cbor-2:serde_cbor_2"
    "webauthn-attestation-ca:webauthn-attestation-ca"
    "serde-wasm-bindgen:serde-wasm-bindgen"
    "web-sys:web-sys"
    "serde-wasm-bindgen:serde-wasm-bindgen"
    "webauthn-rs-proto:webauthn-rs-proto"
    "webauthn-rs-core:webauthn-rs-core"
    "webauthn-rs:webauthn-rs"
    "endian-trait-derive:endian_trait_derive"
    "endian-trait:endian_trait"
    "rustyline:rustyline"
  )

export CARGO=/usr/local/bin/cargo
export RUSTC=/usr/local/bin/rustc

TOTAL=${#RUST_LIBS[@]}
CURRENT=0

for entry in "${RUST_LIBS[@]}"; do
  rust_lib="${entry%%:*}"
  repackage_name="${entry##*:}"
  echo "####################"
  echo "Build start... [${CURRENT}/${TOTAL}]"
  echo "Building rust package ${repackage_name}..."
  echo "CARGO: $($CARGO --version)"
  echo "RUSTC: $($RUSTC --version)"
  echo "DEBCARGO: $(debcargo --version)"
  rm -rf ./build/*
  ./repackage.sh ${repackage_name}
  (
    cd build/${rust_lib}/
    pwd
    yes |mk-build-deps --install --remove; \
    dpkg-buildpackage -b -us -uc
  )
  mkdir -p /tmp/${PKGNAME}-temp
  mkdir -p /tmp/${PKGNAME}
  for deb_pkg in $(find $(pwd)/build/ -name *.deb); do
    cp ${deb_pkg} "/tmp/${PKGNAME}-temp/"
    cp ${deb_pkg} "/tmp/${PKGNAME}/"
  done
  apt install --reinstall -y --allow-downgrades $(ls /tmp/${PKGNAME}-temp/*.deb | grep -v -- 'compact-jwt+msextensions-dev\|-abcdtz_') &&
  rm -rf /tmp/${PKGNAME}-temp
  CURRENT=$((CURRENT + 1))
  echo "Build finished for rust library ${repackage_name}... [${CURRENT}/${TOTAL}]"
done

