#!/bin/bash

set -e

# Function to clean up on exit (Ctrl+C)
cleanup() {
    printf "\033[r"
    printf "\033[${ROWS};1H"
    tput cnorm
    # Add a newline so the prompt appears BELOW the progress bar
    echo ""
    exit
}
trap cleanup SIGINT EXIT

SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)
PKGNAME=$(basename $SCRIPT_DIR)

echo "This is $PKGNAME build scripts"

. ../common.sh

cd $SCRIPT_DIR/$PKGNAME

arch=`arch`
if [[ "$arch" == "loongarch64" || "$arch" == "aarch64" ]];then
  for i in `cat $SCRIPT_DIR/series`; do
    patch --forward -p1 < ../$i || true
  done
fi

RUST_LIBS=(
    "shlex:shlex"
    "unicode-ident:unicode-ident"
    "proc-macro2:proc-macro2"
    "quote:quote"
    "syn:syn"
    "serde-derive:serde_derive"
    "serde-core:serde_core"
    "serde:serde"
    "serde-bytes:serde_bytes"
    "serde-plain:serde_plain"
    "bit-vec:bit-vec"
    "bit-set:bit-set"
    "rustc-std-workspace-core:rustc-std-workspace-core"
    "cfg-if:cfg-if"
    "libc:libc"
    "errno:errno"
    "r-efi:r-efi"
    "anyhow:anyhow"
    "heck:heck"
    "either:either"
    "crossbeam-utils:crossbeam-utils"
    "crossbeam-epoch:crossbeam-epoch"
    "crossbeam-deque:crossbeam-deque"
    "critical-section:critical-section"
    "derive-arbitrary:derive_arbitrary"
    "arbitrary:arbitrary"
    "smallvec:smallvec"
    "parking-lot-core:parking_lot_core"
    "portable-atomic:portable-atomic"
    "once-cell:once_cell"
    "wasm-bindgen-shared:wasm-bindgen-shared"
    "allocator-api2:allocator-api2"
    "bumpalo:bumpalo"
    "wasm-bindgen-macro-support:wasm-bindgen-macro-support"
    "wasm-bindgen-macro:wasm-bindgen-macro"
    "rustversion:rustversion"
    "no-panic:no-panic"
    "itoa:itoa"
    "jobserver:jobserver"
    "cc:cc"
    "compiler-builtins:compiler_builtins"
    "sval-derive-macros:sval_derive_macros"
    "sval:sval"
    "sval-ref:sval_ref"
    "sval-buffer:sval_buffer"
    "typeid:typeid"
    "erased-serde:erased-serde"
    "serde-fmt:serde_fmt"
    "sval-dynamic:sval_dynamic"
    "ryu:ryu"
    "sval-fmt:sval_fmt"
    "sval-nested:sval_nested"
    "sval-serde:sval_serde"
    "sval-json:sval_json"
    "sval-test:sval_test"
    "value-bag-sval2:value-bag-sval2"
    "memchr:memchr"
    "foldhash:foldhash"
    "prettyplease:prettyplease"
    "leb128fmt:leb128fmt"
    "rustc-std-workspace-std:rustc-std-workspace-std"
    "unicode-width:unicode-width"
    "bytemuck-derive:bytemuck_derive"
    "bytemuck:bytemuck"
    "bitflags:bitflags"
    "semver:semver"
    "wasmparser:wasmparser"
    "wasm-encoder:wasm-encoder"
    "fallible-iterator:fallible-iterator"
    "fnv:fnv"
    "stable-deref-trait:stable_deref_trait"
    "linux-raw-sys:linux-raw-sys"
    "rustc-std-workspace-alloc:rustc-std-workspace-alloc"
    "equivalent:equivalent"
    "hashbrown:hashbrown"
    "gimli:gimli"
    "wast:wast"
    "wat:wat"
    "rayon-core:rayon-core"
    "rayon:rayon"
    "id-arena:id-arena"
    "indexmap:indexmap"
    "serde-json:serde_json"
    "serde-test:serde_test"
    "serde-buf:serde_buf"
    "serde-buf:serde_buf"
    "value-bag-serde1:value-bag-serde1"
    "value-bag:value-bag"
    "log:log"
    "memchr:memchr"
    "unicode-xid:unicode-xid"
    "wit-parser:wit-parser"
    "clap-lex:clap_lex"
    "getopts:getopts"
    "pulldown-cmark-escape:pulldown-cmark-escape"
    "unicase:unicase"
    "pulldown-cmark:pulldown-cmark"
    "anstyle:anstyle"
    "clap-derive:clap_derive"
    "utf8parse:utf8parse"
    "zeroize-derive:zeroize_derive"
    "zeroize:zeroize"
    "arrayvec:arrayvec"
    "anstyle-parse:anstyle-parse"
    "anstyle-query:anstyle-query"
    "colorchoice:colorchoice"
    "is-terminal-polyfill:is_terminal_polyfill"
    "anstream:anstream"
    "strsim:strsim"
    "clap-builder:clap_builder"
    "clap:clap"
    "wit-bindgen-core:wit-bindgen-core"
    "topological-sort:topological-sort"
    "dyn-clone:dyn-clone"
    "serde-derive-internals:serde_derive_internals"
    "schemars-derive:schemars_derive"
    "ref-cast-impl:ref-cast-impl"
    "ref-cast:ref-cast"
    "autocfg:autocfg"
    "libm:libm"
    "num-traits:num-traits"
    "num-integer:num-integer"
    "aho-corasick:aho-corasick"
    "regex-syntax:regex-syntax"
    "regex-automata:regex-automata"
    "regex:regex"
    "env-filter:env_filter"
    "jiff-tzdb:jiff-tzdb"
    "jiff-tzdb-platform:jiff-tzdb-platform"
    "portable-atomic-util:portable-atomic-util"
    "portable-atomic:portable-atomic"
    "jiff-static:jiff-static"
    "jiff:jiff"
    "env-logger:env_logger"
    "rand-core:rand_core"
    "rand-xorshift:rand_xorshift"
    "zerocopy-derive:zerocopy-derive"
    "zerocopy:zerocopy"
    "ppv-lite86:ppv-lite86"
    "rand-chacha:rand_chacha"
    "cpufeatures:cpufeatures"
    "typenum:typenum"
    "subtle:subtle"
    "cmov:cmov"
    "ctutils:ctutils"
    "hybrid-array:hybrid-array"
    "crypto-common:crypto-common"
    "block-padding:block-padding"
    "inout:inout"
    "blobby:blobby"
    "block-buffer:block-buffer"
    "cipher:cipher"
    "chacha20:chacha20"
    "winnow:winnow"
    "toml-parser:toml_parser"
    "toml-datetime:toml_datetime"
    "toml-writer:toml_writer"
    "serde-spanned:serde_spanned"
    "toml-edit:toml_edit"
    "proc-macro-crate:proc-macro-crate"
    "borsh-derive:borsh-derive"
    "bytes:bytes"
    "cfg-aliases:cfg_aliases"
    "borsh:borsh"
    "rust-decimal-macros:rust_decimal_macros"
    "rust-decimal:rust_decimal"
    "percent-encoding:percent-encoding"
    "form-urlencoded:form_urlencoded"
    "synstructure:synstructure"
    "zerofrom-derive:zerofrom-derive"
    "zerofrom:zerofrom"
    "writeable:writeable"
    "displaydoc:displaydoc"
    "zerovec-derive:zerovec-derive"
    "databake-derive:databake-derive"
    "databake:databake"
    "twox-hash:twox-hash"
    "zerovec:zerovec"
    "potential-utf:potential_utf"
    "map:map"
    "yoke:yoke"
    "zerovec:zerovec"
    "yoke-derive:yoke-derive"
    "yoke:yoke"
    "zerovec:zerovec"
    "icu-collections:icu_collections"
    "icu-normalizer-data:icu_normalizer_data"
    "litemap:litemap"
    "tinystr:tinystr"
    "icu-locale-core:icu_locale_core"
    "icu-properties-data:icu_properties_data"
    "thiserror-impl-1:thiserror-impl 1"
    "thiserror-impl:thiserror-impl"
    "thiserror-1:thiserror 1"
    "thiserror:thiserror"
    "defmt-parser:defmt-parser"
    "proc-macro-error-attr2:proc-macro-error-attr2"
    "proc-macro-error2:proc-macro-error2"
    "defmt-macros:defmt-macros"
    "defmt:defmt"
    "byteorder:byteorder"
    "hash32:hash32"
    "embedded-io:embedded-io"
    "syn-1:syn 1"
    "ufmt-macros:ufmt-macros"
    "ufmt-write:ufmt-write"
    "ufmt:ufmt"
    "heapless:heapless"
    "cobs:cobs"
    "postcard-derive:postcard-derive"
    "crc-catalog"
    "crc:crc"
    "num-complex:num-complex"
    "approx:approx"
    "nalgebra-macros:nalgebra-macros"
    "num-bigint:num-bigint"
    "num-rational:num-rational"
    "paste-test-suite:paste-test-suite"
    "paste:paste"
    "simba:simba"
    "rawpointer:rawpointer"
    "encase-derive-impl:encase_derive_impl"
    "encase-derive:encase_derive"
    "typewit-proc-macros:typewit_proc_macros"
    "dissimilar:dissimilar"
    "glob:glob"
    "target-triple:target-triple"
    "typewit:typewit"
    "unicode-xid:unicode-xid"
    "const-panic-proc-macros:const_panic_proc_macros"
    "const-panic:const_panic"
    "encase:encase"
    "mint:mint"
    "memoffset:memoffset"
    "speedy-derive:speedy-derive"
    "speedy:speedy"
    "glam:glam"
    "matrixcompare-core:matrixcompare-core"
    "num-cpus:num_cpus"
    "crossbeam-channel:crossbeam-channel"
    "thread-tree:thread-tree"
    "matrixmultiply:matrixmultiply"
    "ucd-trie:ucd-trie"
    "miette-derive:miette-derive"
    "home:home"
    "afl:afl"
    "cpp-demangle:cpp_demangle"
    "addr2line:addr2line"
    "backtrace:backtrace"
    "backtrace-ext:backtrace-ext"
    "miette:miette"
    "pest:pest"
    "const-oid:const-oid"
    "digest:digest"
    "sha2:sha2"
    "pest-meta:pest_meta"
    "pest-generator:pest_generator"
    "pest-derive:pest_derive"
    "nalgebra:nalgebra"
    "postcard:postcard"
    "icu-provider:icu_provider"
    "icu-properties:icu_properties"
    "icu-normalizer:icu_normalizer"
    "idna-adapter:idna_adapter"
    "idna:idna"
    "url:url"
    "uuid:uuid"
    "schemars:schemars"
    "auditable-serde:auditable-serde"
    "wasm-metadata:wasm-metadata"
    "wit-bindgen-rust:wit-bindgen-rust"
    "wit-bindgen-rust-macro:wit-bindgen-rust-macro"
    "wit-bindgen:wit-bindgen"
    "wasip2:wasip2"
    "getrandom:getrandom"
    "rand:rand"
    "quickcheck:quickcheck"
    "bigdecimal:bigdecimal"
    "chrono:chrono"
    "ahash:ahash"
    "wasm-bindgen:wasm-bindgen"
    "js-sys:js-sys"
    "wasm-sync:wasm_sync"
    "serde-test:serde_test"
    "openssl:openssl"
    "openssl-probe:openssl-probe"
    "url:url"
    "futures-core:futures-core"
    "futures-sink:futures-sink"
    "futures-channel:futures-channel"
    "futures-task:futures-task"
    "futures-macro:futures-macro"
    "pin-project-lite:pin-project-lite"
    "slab:slab"
    "futures-io:futures-io"
    "futures-util:futures-util"
    "num-cpus:num_cpus"
    "futures-executor:futures-executor"
    "futures:futures"
    "http-body:http-body"
    "http-body-util:http-body-util"
    "parking-lot:parking_lot"
    "tracing-attributes:tracing-attributes"
    "valuable-derive:valuable-derive"
    "valuable:valuable"
    "tracing-core:tracing-core"
    "tracing:tracing"
    "socket2:socket2"
    "tokio-macros:tokio-macros"
    "signal-hook-registry:signal-hook-registry"
    "tokio:tokio"
    "httparse:httparse"
    "httpdate:httpdate"
    "try-lock:try-lock"
    "want:want"
    "atomic-waker:atomic-waker"
    "tokio-util:tokio-util"
    "h2:h2"
    "hyper:hyper"
    "ipnet:ipnet"
    "tower-service:tower-service"
    "hyper-util:hyper-util"
    "zstd-sys:zstd-sys"
    "zstd-safe:zstd-safe"
    "zstd:zstd"
    "const-format-proc-macros:const_format_proc_macros"
    "const-format:const_format"
    "env-logger:env_logger"
    "xattr:xattr"
    "filetime:filetime"
    "tar:tar"
    "winapi-util:winapi-util"
    "winapi:winapi"
    "same-file:same-file"
    "walkdir:walkdir"
    "sync-wrapper:sync_wrapper"
    "tokio-openssl:tokio-openssl"
    "tokio-stream:tokio-stream"
    "smawk:smawk"
    "unicode-linebreak:unicode-linebreak"
    "textwrap:textwrap"
    "nu-ansi-term:nu-ansi-term"
    "alloca:alloca"
    "criterion-plot:criterion-plot"
    "criterion:criterion"
    "spin:spin"
    "lazy-static:lazy_static"
    "sharded-slab:sharded-slab"
    "thread-local:thread_local"
    "lru:lru"
    "tracing-log:tracing-log"
    "pure-rust-locales:pure-rust-locales"
    "iana-time-zone:iana-time-zone"
    "matchers:matchers"
    "valuable-serde:valuable-serde"
    "tracing-serde:tracing-serde"
    "tracing-subscriber:tracing-subscriber"
    "tracing-journald:tracing-journald"
    "tempfile:tempfile"
    "rustix:rustix"
    "rusty-fork:rusty-fork"
    "proptest:proptest"
    "smartstring:smartstring"
    "rhai-codegen:rhai_codegen"
    "rhai:rhai"
    "rust-embed:rust-embed"
    "handlebars:handlebars"
    "serde-with:serde_with"
    "pam:pam"
    "regex:regex"
    "base64urlsafedata:base64urlsafedata"
    "openssl-macros:openssl-macros"
    "openssl-sys:openssl-sys"
    "compact-jwt:compact_jwt"
    "der-parser:der-parser"
    "serde-cbor:serde_cbor"
    "serde-cbor-2:serde_cbor_2"
    "webauthn-attestation-ca:webauthn-attestation-ca"
    "serde-wasm-bindgen:serde-wasm-bindgen"
    "web-sys:web-sys"
    "serde-wasm-bindgen:serde-wasm-bindgen"
    "webauthn-rs-proto:webauthn-rs-proto"
    "webauthn-rs-core:webauthn-rs-core"
    "webauthn-rs:webauthn-rs"
    "endian-trait-derive:endian_trait_derive"
    "endian-trait:endian_trait"
    "rustyline:rustyline"
  )

export CARGO=/usr/local/bin/cargo
export RUSTC=/usr/local/bin/rustc

TOTAL=${#RUST_LIBS[@]}
CURRENT=0

for entry in "${RUST_LIBS[@]}"; do
  rust_lib="${entry%%:*}"
  repackage_name="${entry##*:}"

  # Print progress bar
  BAR_WIDTH=40
  ROWS=$(tput lines)
  printf "\033[1;$(($ROWS - 1))r"
  printf "\n%.0s" $(seq 1 $ROWS)
  tput civis
  printf "\033[s"
  printf "\033[${ROWS};1H"
  PERCENT=$(( CURRENT * 100 / TOTAL))
  FILLED=$(( CURRENT * BAR_WIDTH / TOTAL))
  EMPTY=$(( BAR_WIDTH - FILLED ))
  BAR=$(printf "%${FILLED}s" | tr ' ' '#')
  SPACE=$(printf "%${EMPTY}s" | tr ' ' '-')
  printf "\033[K\e[30;46m[%s%s] %d%% (%d/%d) building ${repackage_name}...\e[0m" "$BAR" "$SPACE" "$PERCENT" "$CURRENT" "$TOTAL"
  printf "\033[u"

  echo "####################"
  echo "Build start... [${CURRENT}/${TOTAL}]"
  echo "Building rust package ${repackage_name}..."
  echo "CARGO: $($CARGO --version)"
  echo "RUSTC: $($RUSTC --version)"
  echo "DEBCARGO: $(debcargo --version)"
  rm -rf ./build/*
  ./repackage.sh ${repackage_name}
  (
    cd build/${rust_lib}/
    pwd
    yes |mk-build-deps --install --remove; \
    dpkg-buildpackage -b -us -uc
  )
  mkdir -p /tmp/${PKGNAME}-temp
  mkdir -p /tmp/${PKGNAME}
  for deb_pkg in $(find $(pwd)/build/ -name "*.deb"); do
    cp ${deb_pkg} "/tmp/${PKGNAME}-temp/"
    cp ${deb_pkg} "/tmp/${PKGNAME}/"
  done
  apt install --reinstall -y --allow-downgrades --reinstall $(ls /tmp/${PKGNAME}-temp/*.deb | grep -v -- 'compact-jwt+msextensions-dev\|-abcdtz_') || exit 1 &&
  rm -rf /tmp/${PKGNAME}-temp
  CURRENT=$((CURRENT + 1))
  echo "Build finished for rust library ${repackage_name}... [${CURRENT}/${TOTAL}]"
  # Remove the patch
  rm -rf ./src/${repackage_name}/debian/patches/
done

