#!/bin/bash

set -e

SCRIPT_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)
PKGNAME=$(basename $SCRIPT_DIR)

echo "This is $PKGNAME build scripts"

. ../common.sh

cd $SCRIPT_DIR/$PKGNAME

RUST_LIBS=(
    "shlex:shlex:patches:notvendor"
    "unicode-ident:unicode-ident:patches:notvendor"
    "proc-macro2:proc-macro2:patches:notvendor"
    "quote:quote:patches:notvendor"
    "syn-1:syn 1:patches:notvendor"
    "syn:syn:patches:notvendor"
    "serde-derive:serde_derive:patches:notvendor"
    "serde-core:serde_core:patches:notvendor"
    "serde:serde:patches:notvendor"
    "serde-bytes:serde_bytes:patches:notvendor"
    "serde-plain:serde_plain:patches:notvendor"
    "bit-vec:bit-vec:patches:notvendor"
    "bit-set:bit-set:patches:notvendor"
    "rustc-std-workspace-core:rustc-std-workspace-core:patches:notvendor"
    "cfg-if:cfg-if:patches:notvendor"
    "libc:libc:patches:notvendor"
    "errno:errno:patches:notvendor"
    "r-efi:r-efi:patches:notvendor"
    "anyhow:anyhow:patches:notvendor"
    "heck:heck:none:notvendor"
    "either:either:patches:notvendor"
    "crossbeam-utils:crossbeam-utils:patches:notvendor"
    "crossbeam-epoch:crossbeam-epoch:patches:notvendor"
    "crossbeam-deque:crossbeam-deque:patches:notvendor"
    "critical-section:critical-section:patches:notvendor"
    "derive-arbitrary:derive_arbitrary:patches:notvendor"
    "arbitrary:arbitrary:patches:notvendor"
    "smallvec:smallvec:patches:notvendor"
    "parking-lot-core:parking_lot_core:patches:notvendor"
    "portable-atomic:portable-atomic:patches:notvendor"
    "once-cell:once_cell:patches:notvendor"
    "wasm-bindgen-shared:wasm-bindgen-shared:patches:notvendor"
    "allocator-api2:allocator-api2:patches:notvendor"
    "bumpalo:bumpalo:patches:notvendor"
    "wasm-bindgen-macro-support:wasm-bindgen-macro-support:patches:notvendor"
    "wasm-bindgen-macro:wasm-bindgen-macro:patches:notvendor"
    "rustversion:rustversion:patches:notvendor"
    "no-panic:no-panic:patches:notvendor"
    "itoa:itoa:patches:notvendor"
    "jobserver:jobserver:patches:notvendor"
    "find-msvc-tools:find-msvc-tools:patches:notvendor"
    "cc:cc:patches:notvendor"
    "compiler-builtins:compiler_builtins:patches:notvendor"
    "sval-derive-macros:sval_derive_macros:patches:notvendor"
    "sval:sval:patches:notvendor"
    "sval-ref:sval_ref:patches:notvendor"
    "sval-buffer:sval_buffer:patches:notvendor"
    "typeid:typeid:patches:notvendor"
    "erased-serde:erased-serde:patches:notvendor"
    "serde-fmt:serde_fmt:patches:notvendor"
    "sval-dynamic:sval_dynamic:patches:notvendor"
    "ryu:ryu:patches:notvendor"
    "sval-fmt:sval_fmt:patches:notvendor"
    "sval-nested:sval_nested:patches:notvendor"
    "sval-serde:sval_serde:patches:notvendor"
    "sval-json:sval_json:patches:notvendor"
    "sval-test:sval_test:patches:notvendor"
    "value-bag-sval2:value-bag-sval2:patches:notvendor"
    "memchr:memchr:patches:notvendor"
    "foldhash:foldhash:patches:notvendor"
    "prettyplease:prettyplease:patches:notvendor"
    "leb128fmt:leb128fmt:patches:notvendor"
    "rustc-std-workspace-std:rustc-std-workspace-std:patches:notvendor"
    "unicode-width:unicode-width:patches:notvendor"
    "bytemuck-derive:bytemuck_derive:patches:notvendor"
    "bytemuck:bytemuck:patches:notvendor"
    "bitflags:bitflags:patches:notvendor"
    "semver:semver:patches:notvendor"
    "rustc-version:rustc_version:patches:notvendor"
    "wasmparser:wasmparser:patches:notvendor"
    "wasm-encoder:wasm-encoder:patches:notvendor"
    "fallible-iterator:fallible-iterator:patches:notvendor"
    "fnv:fnv:patches:notvendor"
    "stable-deref-trait:stable_deref_trait:patches:notvendor" # TODO duplicate
    "linux-raw-sys:linux-raw-sys:patches:notvendor" # TODO duplicate
    "rustc-std-workspace-alloc:rustc-std-workspace-alloc:patches:notvendor"
    "equivalent:equivalent:patches:notvendor"
    "hashbrown:hashbrown:patches:notvendor"
    "gimli:gimli:patches:notvendor"
    "wast:wast:patches:notvendor"
    "wat:wat:patches:notvendor"
    "rayon-core:rayon-core:patches:notvendor"
    "rayon:rayon:patches:notvendor"
    "id-arena:id-arena:patches:notvendor"
    "indexmap:indexmap:patches:notvendor"
    "zmij:zmij:patches:notvendor"
    "serde-json:serde_json:patches:notvendor"
    "serde-test:serde_test:patches:notvendor" # TODO duplicate
    "serde-buf:serde_buf:patches:notvendor"
    "value-bag-serde1:value-bag-serde1:patches:notvendor"
    "value-bag:value-bag:patches:notvendor"
    "log:log:patches:notvendor"
    "memchr:memchr:none:notvendor"
    "unicode-xid:unicode-xid:patches:notvendor" # TODO duplicate
    "wit-parser:wit-parser:patches:notvendor"
    "clap-lex:clap_lex:patches:notvendor"
    "getopts:getopts:patches:notvendor"
    "pulldown-cmark-escape:pulldown-cmark-escape:patches:notvendor"
    "unicase:unicase:patches:notvendor"
    "pulldown-cmark:pulldown-cmark:patches:notvendor"
    "anstyle:anstyle:patches:notvendor"
    "clap-derive:clap_derive:patches:notvendor"
    "utf8parse:utf8parse:patches:notvendor"
    "zeroize-derive:zeroize_derive:patches:notvendor"
    "zeroize:zeroize:patches:notvendor"
    "arrayvec:arrayvec:patches:notvendor"
    "anstyle-parse:anstyle-parse:patches:notvendor"
    "anstyle-query:anstyle-query:patches:notvendor"
    "colorchoice:colorchoice:patches:notvendor"
    "is-terminal-polyfill:is_terminal_polyfill:patches:notvendor"
    "anstream:anstream:patches:notvendor"
    "strsim:strsim:patches:notvendor"
    "clap-builder:clap_builder:patches:notvendor"
    "clap:clap:patches:notvendor"
    "wit-bindgen-core:wit-bindgen-core:patches:notvendor"
    "topological-sort:topological-sort:patches:notvendor"
    "dyn-clone:dyn-clone:patches:notvendor"
    "serde-derive-internals:serde_derive_internals:patches:notvendor"
    "schemars-derive:schemars_derive:patches:notvendor"
    "ref-cast-impl:ref-cast-impl:patches:notvendor"
    "ref-cast:ref-cast:patches:notvendor"
    "autocfg:autocfg:patches:notvendor"
    "libm:libm:patches:notvendor"
    "num-traits:num-traits:patches:notvendor"
    "num-integer:num-integer:patches:notvendor"
    "aho-corasick:aho-corasick:patches:notvendor"
    "regex-syntax:regex-syntax:patches:notvendor"
    "regex-automata:regex-automata:patches:notvendor"
    "regex:regex:none:notvendor"
    "env-filter:env_filter:patches:notvendor"
    "jiff-tzdb:jiff-tzdb:patches:notvendor"
    "jiff-tzdb-platform:jiff-tzdb-platform:patches:notvendor"
    "portable-atomic-util:portable-atomic-util:patches:notvendor"
    "portable-atomic:portable-atomic:none:notvendor" # TODO duplicate
    "jiff-static:jiff-static:patches:notvendor"
    "jiff:jiff:patches:notvendor"
    "env-logger:env_logger:patches:notvendor"
    "rand-core:rand_core:patches:notvendor" # TODO duplicate
    "rand-xorshift:rand_xorshift:none:notvendor" # TODO duplicate
    "zerocopy-derive:zerocopy-derive:patches:notvendor"
    "zerocopy:zerocopy:patches:notvendor"
    "ppv-lite86:ppv-lite86:patches:notvendor"
    "cpufeatures:cpufeatures:patches:notvendor"
    "radium:radium:patches:notvendor"
    "funty:funty:patches:notvendor"
    "tap:tap:patches:notvendor"
    "traitobject:traitobject:patches:notvendor"
    "wyz:wyz:patches:notvendor"
    "bitvec:bitvec:patches:notvendor"
    "derive-more-impl:derive_more-impl:patches:notvendor"
    "derive-more:derive_more:patches:notvendor"
    "byte-slice-cast:byte-slice-cast:patches:notvendor"
    "const-format-proc-macros:const_format_proc_macros:patches:notvendor"
    "const-format:const_format:patches:notvendor"
    "impl-trait-for-tuples:impl-trait-for-tuples:patches:notvendor"
    "winnow:winnow:patches:notvendor"
    "toml-parser:toml_parser:patches:notvendor"
    "toml-datetime:toml_datetime:patches:notvendor"
    "toml-writer:toml_writer:patches:notvendor"
    "serde-spanned:serde_spanned:patches:notvendor"
    "toml-edit:toml_edit:patches:notvendor"
    "proc-macro-crate:proc-macro-crate:patches:notvendor"
    "bytes:bytes:patches:notvendor"
    "parity-scale-codec-derive:parity-scale-codec-derive:patches:notvendor"
    "parity-scale-codec:parity-scale-codec:patches:notvendor"
    "scale-info-derive:scale-info-derive:patches:notvendor"
    "scale-info:scale-info:patches:notvendor"
    "typenum:typenum:patches:notvendor"
    "subtle:subtle:patches:notvendor"
    "cmov:cmov:patches:notvendor"
    "ctutils:ctutils:patches:notvendor"
    "hybrid-array:hybrid-array:patches:notvendor"
    "crypto-common:crypto-common:patches:notvendor"
    "block-padding:block-padding:patches:notvendor"
    "inout:inout:patches:notvendor"
    "blobby:blobby:patches:notvendor"
    "block-buffer:block-buffer:patches:notvendor"
    "cipher:cipher:patches:notvendor"
    "borsh-derive:borsh-derive:patches:notvendor"
    "cfg-aliases:cfg_aliases:patches:notvendor"
    "borsh:borsh:patches:notvendor"
    "rust-decimal-macros:rust_decimal_macros:patches:notvendor"
    "rust-decimal:rust_decimal:patches:notvendor"
    "percent-encoding:percent-encoding:patches:notvendor"
    "form-urlencoded:form_urlencoded:patches:notvendor"
    "synstructure:synstructure:patches:notvendor"
    "zerofrom-derive:zerofrom-derive:patches:notvendor"
    "zerofrom:zerofrom:patches:notvendor"
    "writeable:writeable:patches:notvendor"
    "displaydoc:displaydoc:patches:notvendor"
    "zerovec-derive:zerovec-derive:patches:notvendor"
    "databake-derive:databake-derive:patches:notvendor"
    "databake:databake:patches:notvendor"
    "twox-hash:twox-hash:patches:notvendor"
    "zerovec:zerovec:patches:notvendor" # TODO duplicate
    "potential-utf:potential_utf:patches:notvendor"
    "map:map:patches:notvendor"
    "yoke:yoke:patches:notvendor" # TODO duplicate
    "zerovec:zerovec:none:notvendor"
    "yoke-derive:yoke-derive:patches:notvendor"
    "yoke:yoke:none:notvendor"
    "zerovec:zerovec:none:notvendor"
    "litemap:litemap:patches:notvendor"
    "zerotrie:zerotrie:patches:notvendor"
    "icu-collections:icu_collections:patches:notvendor"
    "icu-normalizer-data:icu_normalizer_data:patches:notvendor"
    "tinystr:tinystr:patches:notvendor"
    "icu-locale-core:icu_locale_core:patches:notvendor"
    "icu-properties-data:icu_properties_data:patches:notvendor"
    "thiserror-impl-1:thiserror-impl 1:patches:notvendor"
    "thiserror-impl:thiserror-impl:patches:notvendor"
    "thiserror-1:thiserror 1:patches:notvendor"
    "thiserror:thiserror:patches:notvendor"
    "defmt-parser:defmt-parser:patches:notvendor"
    "proc-macro-error-attr2:proc-macro-error-attr2:patches:notvendor"
    "proc-macro-error2:proc-macro-error2:patches:notvendor"
    "defmt-macros:defmt-macros:patches:notvendor"
    "defmt:defmt:patches:notvendor"
    "byteorder:byteorder:patches:notvendor"
    "hash32:hash32:patches:notvendor"
    "embedded-io:embedded-io:patches:notvendor"
    "ufmt-macros:ufmt-macros:patches:notvendor"
    "ufmt-write:ufmt-write:patches:notvendor"
    "ufmt:ufmt:patches:notvendor"
    "heapless:heapless:patches:notvendor"
    "cobs:cobs:patches:notvendor"
    "postcard-derive:postcard-derive:patches:notvendor"
    "crc-catalog:crc-catalog:patches:notvendor"
    "crc:crc:patches:notvendor"
    "num-complex:num-complex:patches:notvendor"
    "approx:approx:patches:notvendor"
    "nalgebra-macros:nalgebra-macros:patches:notvendor"
    "num-bigint:num-bigint:patches:notvendor"
    "num-rational:num-rational:patches:notvendor"
    "paste-test-suite:paste-test-suite:patches:notvendor"
    "paste:paste:patches:notvendor"
    "simba:simba:patches:notvendor"
    "rawpointer:rawpointer:patches:notvendor"
    "encase-derive-impl:encase_derive_impl:patches:notvendor"
    "encase-derive:encase_derive:patches:notvendor"
    "typewit-proc-macros:typewit_proc_macros:patches:notvendor"
    "dissimilar:dissimilar:patches:notvendor"
    "glob:glob:patches:notvendor"
    "target-triple:target-triple:patches:notvendor"
    "typewit:typewit:patches:notvendor"
    "unicode-xid:unicode-xid:none:notvendor"
    "const-panic-proc-macros:const_panic_proc_macros:patches:notvendor"
    "const-panic:const_panic:patches:notvendor"
    "encase:encase:patches:notvendor"
    "mint:mint:patches:notvendor"
    "memoffset:memoffset:patches:notvendor"
    "speedy-derive:speedy-derive:patches:notvendor"
    "speedy:speedy:patches:notvendor"
    "glam:glam:patches:notvendor"
    "matrixcompare-core:matrixcompare-core:patches:notvendor"
    "num-cpus:num_cpus:patches:notvendor"
    "crossbeam-channel:crossbeam-channel:patches:notvendor"
    "thread-tree:thread-tree:patches:notvendor"
    "matrixmultiply:matrixmultiply:patches:notvendor"
    "ucd-trie:ucd-trie:patches:notvendor"
    "miette-derive:miette-derive:patches:notvendor"
    "home:home:patches:notvendor"
    "xdg:xdg:patches:notvendor"
    "afl:afl:patches:notvendor"
    "cpp-demangle:cpp_demangle:patches:notvendor"
    "memmap:memmap:patches:notvendor"
    "crc32fast:crc32fast:patches:notvendor"
    "adler2:adler2:patches:notvendor"
    "simd-adler32:simd-adler32:patches:notvendor"
    "miniz-oxide:miniz_oxide:patches:notvendor"
    "cloudflare-zlib-sys:cloudflare-zlib-sys:patches:notvendor"
    "litrs:litrs:patches:notvendor"
    "document-features:document-features:patches:notvendor"
    "cmake:cmake:patches:notvendor"
    "pkg-config:pkg-config:patches:notvendor"
    "vcpkg:vcpkg:patches:notvendor"
    "libz-sys:libz-sys:patches:notvendor"
    "zlib-rs:zlib-rs:patches:notvendor"
    "flate2:flate2:patches:notvendor"
    "fastrand:fastrand:patches:notvendor"
    "ruzstd:ruzstd:patches:notvendor"
    "object:object:patches:notvendor"
    "memmap2:memmap2:patches:notvendor"
    "rustc-demangle:rustc-demangle:patches:notvendor"
    "typed-arena:typed-arena:patches:notvendor"
    "addr2line:addr2line:patches:notvendor"
    "backtrace:backtrace:patches:notvendor"
    "backtrace-ext:backtrace-ext:patches:notvendor"
    "smawk:smawk:patches:notvendor"
    "unicode-linebreak:unicode-linebreak:patches:notvendor"
    "bincode:bincode:patches:notvendor"
    "utf8-ranges:utf8-ranges:patches:notvendor"
    "fst:fst:patches:notvendor"
    "hyphenation-commons:hyphenation_commons:patches:notvendor"
    "tinyvec-macros:tinyvec_macros:patches:notvendor"
    "faster-hex:faster-hex:patches:notvendor"
    "version-check:version_check:none:notvendor"
    "generic-array-0.14:generic-array 0:patches:notvendor"
    "generic-array:generic-array:patches:notvendor"
    "tinyvec:tinyvec:patches:notvendor"
    "unicode-normalization:unicode-normalization:patches:notvendor"
    "hyphenation:hyphenation:patches:notvendor"
    "textwrap:textwrap:patches:notvendor"
    "miette:miette:patches:notvendor"
    "pest:pest:patches:notvendor"
    "const-oid:const-oid:patches:notvendor"
    "digest:digest:patches:notvendor"
    "sha2:sha2:patches:notvendor"
    "pest-meta:pest_meta:patches:notvendor"
    "pest-generator:pest_generator:patches:notvendor"
    "pest-derive:pest_derive:patches:notvendor"
    "cast:cast:patches:notvendor"
    "itertools:itertools:none:notvendor"
    "alloca:alloca:patches:notvendor"
    "criterion-plot:criterion-plot:patches:notvendor"
    "ciborium-io:ciborium-io:patches:notvendor"
    "crunchy:crunchy:patches:notvendor"
    "half-2:half-2:patches:notvendor"
    "half:half:patches:notvendor"
    "ciborium-ll:ciborium-ll:patches:notvendor"
    "ciborium:ciborium:patches:notvendor"
    "oorandom:oorandom:patches:notvendor"
    "winapi-i686-pc-windows-gnu:winapi-i686-pc-windows-gnu:patches:notvendor"
    "winapi-x86-64-pc-windows-gnu:winapi-x86_64-pc-windows-gnu:patches:notvendor"
    "winapi:winapi:patches:notvendor"
    "page-size:page_size:patches:notvendor"
    "tinytemplate:tinytemplate:patches:notvendor"
    "scopeguard:scopeguard:patches:notvendor"
    "stable-deref-trait:stable_deref_trait:none:notvendor"
    "owning-ref:owning_ref:patches:notvendor"
    "lock-api:lock_api:patches:notvendor"
    "once:once:patches:notvendor"
    "spin:spin:patches:notvendor"
    "lazy-static:lazy_static:patches:notvendor"
    "futures-core:futures-core:patches:notvendor"
    "futures-sink:futures-sink:patches:notvendor"
    "futures-channel:futures-channel:patches:notvendor"
    "futures-task:futures-task:patches:notvendor"
    "futures-macro:futures-macro:patches:notvendor"
    "pin-project-lite:pin-project-lite:patches:notvendor"
    "slab:slab:patches:notvendor"
    "futures-io:futures-io:patches:notvendor"
    "pin-utils:pin-utils:patches:notvendor"
    "futures-util:futures-util:patches:notvendor"
    "futures-executor:futures-executor:patches:notvendor"
    "futures:futures:patches:notvendor"
    "wit-bindgen:wit-bindgen:patches:notvendor"
    "wasip2:wasip2:patches:notvendor"
    "http:http:patches:notvendor"
    "http-body:http-body:patches:notvendor"
    "wasip3:wasip3:patches:notvendor"
    "getrandom:getrandom:patches:notvendor"
    "rand-core:rand_core:none:notvendor"
    "rand-chacha:rand_chacha:patches:notvendor"
    "rand:rand:patches:notvendor" # TODO duplicate
    "rand-xorshift:rand_xorshift:patches:notvendor"
    "rand:rand:none:notvendor"
    "quick-error:quick-error:patches:notvendor"
    "unarray:unarray:patches:notvendor"
    "base64:base64:patches:notvendor"
    "hex:hex:patches:notvendor"
    "ident-case:ident_case:patches:notvendor"
    "darling-core:darling_core:patches:notvendor"
    "darling-macro:darling_macro:patches:notvendor"
    "darling:darling:patches:notvendor"
    "serde-with-macros:serde_with_macros:patches:notvendor"
    "serde-with:serde_with:patches:notvendor"
    "rand-distr:rand_distr:patches:notvendor"
    "nalgebra:nalgebra:patches:notvendor"
    "icu-provider:icu_provider:patches:notvendor"
    "unicode-bidi:unicode-bidi:patches:notvendor"
    "icu-properties:icu_properties:patches:notvendor"
    "utf16-iter:utf16_iter:patches:notvendor"
    "utf8-iter:utf8_iter:patches:notvendor"
    "write16:write16:patches:notvendor"
    "icu-normalizer:icu_normalizer:patches:notvendor"
    "idna-adapter:idna_adapter:patches:notvendor"
    "idna:idna:patches:notvendor"
    "url:url:patches:notvendor"
    "atomic:atomic:patches:notvendor"
    "sha1-smol:sha1_smol:patches:notvendor"
    "uuid-rng-internal:uuid-rng-internal:patches:notvendor"
    "uuid:uuid:patches:notvendor"
    "schemars:schemars:patches:notvendor"
    "auditable-serde:auditable-serde:patches:notvendor"
    "wasm-metadata:wasm-metadata:patches:notvendor"
    "wasmparser:wasmparser:none:notvendor"
    "wit-component:wit-component:patches:notvendor"
    "wit-bindgen-core:wit-bindgen-core:patches:notvendor"
    "wit-bindgen-rust:wit-bindgen-rust:patches:notvendor"
    "wit-bindgen-rust-macro:wit-bindgen-rust-macro:none:notvendor"
    "bigdecimal:bigdecimal:patches:notvendor"
    "windows-link:windows-link:patches:notvendor"
    "chrono:chrono:patches:notvendor"
    "crunchy:crunchy:none:notvendor" # TODO duplicate
    "tiny-keccak:tiny-keccak:patches:notvendor"
    "ahash:ahash:patches:notvendor"
    "wasm-bindgen:wasm-bindgen:patches:notvendor"
    "js-sys:js-sys:none:notvendor"
    "md-5:md-5:patches:notvendor"
    "uuid:uuid:patches_2:notvendor"
    "getrandom:getrandom:none:notvendor"
    "serde-test:serde_test:none:notvendor"
    "http-body-util:http-body-util:patches:notvendor"
    "parking-lot:parking_lot:patches:notvendor"
    "tracing-attributes:tracing-attributes:patches:notvendor"
    "valuable-derive:valuable-derive:patches:notvendor"
    "valuable:valuable:patches:notvendor"
    "tracing-core:tracing-core:patches:notvendor"
    "tracing:tracing:patches:notvendor"
    "socket2:socket2:patches:notvendor"
    "tokio-macros:tokio-macros:none:notvendor"
    "signal-hook-registry:signal-hook-registry:patches:notvendor"
    "httparse:httparse:patches:notvendor"
    "httpdate:httpdate:patches:notvendor"
    "try-lock:try-lock:patches:notvendor"
    "want:want:patches:notvendor"
    "atomic-waker:atomic-waker:patches:notvendor"
    "ipnet:ipnet:patches:notvendor"
    "tower-service:tower-service:patches:notvendor"
    "const-format-proc-macros:const_format_proc_macros:none:notvendor"
    "filetime:filetime:patches:notvendor"
    "sync-wrapper:sync_wrapper:patches:notvendor"
    "nu-ansi-term:nu-ansi-term:patches:notvendor"
    "sharded-slab:sharded-slab:patches:notvendor"
    "thread-local:thread_local:patches:notvendor"
    "lru:lru:patches:notvendor"
    "tracing-log:tracing-log:patches:notvendor"
    "pure-rust-locales:pure-rust-locales:patches:notvendor"
    "matchers:matchers:patches:notvendor"
    "valuable-serde:valuable-serde:patches:notvendor"
    "tracing-serde:tracing-serde:patches:notvendor"
    "tracing-core:tracing-core:none:notvendor" # TODO duplicate
    "tracing-subscriber:tracing-subscriber:patches:notvendor"
    "tracing-journald:tracing-journald:patches:notvendor"
    "rhai-codegen:rhai_codegen:patches:notvendor"
    "static-assertions:static_assertions:patches:notvendor"
    "smartstring:smartstring:patches:notvendor"
    "malloc-size-of:malloc_size_of:patches:notvendor"
    "thin-vec:thin-vec:patches:notvendor"
    "pam-sys:pam-sys:patches:notvendor"
    "uzers:uzers:patches:notvendor"
    "pam:pam:patches:notvendor"
    "regex:regex:none:notvendor" # TODO duplicate
    "pastey:pastey:patches:notvendor"
    "base64urlsafedata:base64urlsafedata:patches:notvendor"
    "openssl-macros:openssl-macros:patches:notvendor"
    "serde-cbor:serde_cbor:patches:notvendor"
    "serde-cbor-2:serde_cbor_2:patches:notvendor"
    "serde-wasm-bindgen:serde-wasm-bindgen:patches:notvendor"
    "web-sys:web-sys:patches:notvendor"
    "webauthn-rs-proto:webauthn-rs-proto:patches:notvendor"
    "endian-trait-derive:endian_trait_derive:patches:notvendor"
    "endian-trait:endian_trait:patches:notvendor"
    "nix:nix:none:notvendor"
    "endian-type:endian-type:patches:notvendor"
    "minimal-lexical:minimal-lexical:patches:notvendor"
    "nom:nom:patches:notvendor"
    "cexpr:cexpr:patches:notvendor"
    "regex-lite:regex-lite:patches:notvendor"
    "libloading:libloading:patches:notvendor"
    "clang-sys:clang-sys:patches:notvendor"
    "llvm-sys:llvm-sys:patches:notvendor"
    "rustc-hash:rustc-hash:patches:notvendor"
    "annotate-snippets:annotate-snippets:patches:notvendor"
    "bindgen:bindgen:patches:notvendor"
    "sc:sc:patches:notvendor"
    "io-uring:io-uring:patches:notvendor"
    "tokio-macros:tokio-macros:none:notvendor" # TODO duplicate
    "tokio:tokio:patches:notvendor"
    "tokio-util:tokio-util:patches:notvendor"
    "h2:h2:patches:notvendor"
    "hyper:hyper:patches:notvendor"
    "hyper-util:hyper-util:patches:notvendor"
    "zstd-sys:zstd-sys:patches:notvendor"
    "zstd-safe:zstd-safe:patches:notvendor"
    "zstd:zstd:patches:notvendor"
    "openssl-probe:openssl-probe:patches:notvendor"
    "foreign-types-macros:foreign-types-macros:patches:notvendor"
    "foreign-types-shared-0.1:foreign-types-shared 0.1:patches:notvendor"
    "foreign-types-0.3:foreign-types 0.3:patches:notvendor"
    "dunce:dunce:patches:notvendor"
    "fs-extra:fs_extra:patches:notvendor"
    "aws-lc-sys:aws-lc-sys:patches:notvendor"
    "aws-lc-fips-sys:aws-lc-fips-sys:patches:notvendor"
    "bssl-sys:bssl-sys:patches:notvendor"
    "openssl-src:openssl-src:patches:notvendor"
    "openssl-sys:openssl-sys:patches:notvendor"
    "openssl:openssl:patches:notvendor"
    "tokio-openssl:tokio-openssl:patches:notvendor"
    "wasm-sync:wasm_sync:patches:notvendor"
    "linux-raw-sys:linux-raw-sys:none:notvendor"
    "rustix:rustix:patches:notvendor"
    "xattr:xattr:patches:notvendor"
    "tar:tar:patches:notvendor"
    "tokio-stream:tokio-stream:patches:notvendor"
    "web-time:web-time:patches:notvendor"
    "core-error:core-error:patches:notvendor"
    "rhai:rhai:patches:notvendor"
    "heck:heck:none:notvendor" # TODO duplicate
    "derive-builder-core:derive_builder_core:patches:notvendor"
    "derive-builder-macro:derive_builder_macro:patches:notvendor"
    "num-modular:num-modular:patches:notvendor"
    "num-order:num-order:patches:notvendor"
    "derive-builder:derive_builder:patches:notvendor"
    "handlebars:handlebars:patches:notvendor"
    "compact-jwt:compact_jwt:patches:notvendor"
    "asn1-rs-derive:asn1-rs-derive:patches:notvendor"
    "asn1-rs-impl:asn1-rs-impl:patches:notvendor"
    "rusticata-macros:rusticata-macros:patches:notvendor"
    "deranged-macros:deranged-macros:patches:notvendor"
    "powerfmt-macros:powerfmt-macros:patches:notvendor"
    "powerfmt:powerfmt:patches:notvendor"
    "num-conv:num-conv:patches:notvendor"
    "deranged:deranged:patches:notvendor"
    "time-core:time-core:patches:notvendor"
    "time-macros:time-macros:patches:notvendor"
    "num-threads:num_threads:patches:notvendor"
    "time:time:patches:notvendor"
    "cookie-factory:cookie-factory:patches:notvendor"
    "asn1-rs:asn1-rs:patches:notvendor"
    "der-parser:der-parser:patches:notvendor"
    "webauthn-attestation-ca:webauthn-attestation-ca:patches:notvendor"
    "data-encoding:data-encoding:patches:notvendor"
    "oid-registry:oid-registry:patches:notvendor"
    "x509-parser:x509-parser:patches:notvendor"
    "webauthn-rs-core:webauthn-rs-core:patches:notvendor"
    "webauthn-rs:webauthn-rs:patches:notvendor"
    "wit-bindgen:wit-bindgen:patches_2:notvendor"
    "wasip2:wasip2:patches_2:notvendor"
    "wasi:wasi:patches:notvendor"
    "mio:mio:patches:notvendor"
    "tokio:tokio:patches_2:notvendor"
    "winapi-util:winapi-util:patches:notvendor"
    "same-file:same-file:none:notvendor"
    "walkdir:walkdir:none:notvendor"
    "schannel:schannel:patches:notvendor"
    "core-foundation-sys:core-foundation-sys:none:notvendor"
    "core-foundation:core-foundation:none:notvendor"
    "security-framework-sys:security-framework-sys:none:notvendor"
    "security-framework:security-framework:none:notvendor"
    "untrusted:untrusted:none:notvendor"
    "tempfile:tempfile:patches:notvendor"
    "native-tls:native-tls:none:notvendor"
    "untrusted:untrusted:none:notvendor"
    "aws-lc-rs:aws-lc-rs:patches:notvendor"
    "rustls-pki-types:rustls-pki-types:none:notvendor"
    "rustls-webpki:rustls-webpki:patches:notvendor"
    "rustls:rustls:patches:notvendor"
    "ureq-proto:ureq-proto:none:notvendor"
    "utf8-zero:utf8-zero:none:notvendor"
    "der-derive:der_derive:none:notvendor"
    "der:der:patches:notvendor"
    "quick-error:quick-error:none:notvendor"
    "wait-timeout:wait-timeout:none:notvendor"
    "rusty-fork:rusty-fork:patches:notvendor"
    "unicode-segmentation:unicode-segmentation:none:notvendor"
    "convert-case:convert_case:none:notvendor"
    "proptest-macro:proptest-macro:none:notvendor"
    "proptest:proptest:patches_2:notvendor"
    "base64ct:base64ct:none:notvendor"
    "pem-rfc7468:pem-rfc7468:none:notvendor"
    "der:der:patches_2:notvendor"
    "ureq:ureq:patches:notvendor"
    "rustyline-derive:rustyline-derive:none:notvendor"
    "rustyline:rustyline:patches:notvendor"
    "handlebars:handlebars:patches_2:notvendor"
    "base32:base32:none:notvendor"
    "rustc-hash-1:rustc-hash 1.0.1:none:notvendor"
    "lazycell:lazycell:patches:notvendor"
    "itertools-0.12:itertools 0.12:none:vendor"
    "bindgen-0.69:bindgen 0.69:none:vendor"
    "getrandom-0.2:getrandom 0.2:none:vendor"
    "rand-core-0.6:rand_core 0.6:none:vendor"
    "password-hash:password-hash:none:vendor"
    "argon2:argon2:none:vendor"
    "buffered-reader:buffered-reader:none:vendor"
    "bzip2-sys:bzip2-sys:none:notvendor"
    "libbz2-rs-sys:libbz2-rs-sys:none:notvendor"
    "bzip2:bzip2:none:notvendor"
    "android-system-properties:android_system_properties:none:notvendor"
    "iana-time-zone-haiku:iana-time-zone-haiku:patches:notvendor"
    "iana-time-zone:iana-time-zone:patches:notvendor"
    "chrono:chrono:patches_2:notvendor"
    "lalrpop-util:lalrpop-util:none:notvendor"
    "ascii-canvas:ascii-canvas:none:vendor"
    "ena:ena:none:vendor"
    "petgraph:petgraph:none:vendor"
    "pico-args:pico-args:none:vendor"
    "sha3:sha3:none:vendor"
    "term:term:patches:notvendor"
    "new-debug-unreachable:new_debug_unreachable:none:notvendor"
    "phf-shared:phf_shared:none:vendor"
    "precomputed-hash:precomputed-hash:none:notvendor"
    "siphasher:siphasher:none:vendor"
    "string-cache:string_cache:none:notvendor"
    "fixedbitset:fixedbitset:none:notvendor"
    "keccak:keccak:none:notvendor"
    "lalrpop:lalrpop:patches:notvendor"
    "memsec:memsec:none:vendor"
    "nettle:nettle:none:vendor"
    "digest-0.10:digest 0.10:none:vendor"
    "block-buffer-0.10:block-buffer 0.10:none:vendor"
    "crypto-common-0.1:crypto-common 0.1:none:vendor"
    "generic-array-0.14:generic-array 0.14:none:vendor"
    "sha1collisiondetection:sha1collisiondetection:none:vendor"
    "xxhash-rust:xxhash-rust:patches:vendor"
    "blake2:blake2:none:vendor"
    "cpufeatures-0.2:cpufeatures 0.2:none:vendor"
    "libbz2-rs-sys-0.1:libbz2-rs-sys 0.1:none:notvendor"
    "bzip2-0.5:bzip2 0.5:none:notvendor"
    "nettle-sys:nettle-sys:none:vendor"
    "wasi-0.11:wasi 0.11:none:vendor"
    "sequoia-openpgp:sequoia-openpgp:patches:vendor"
    "fmt2io:fmt2io:none:notvendor"
    "rfc822-like:rfc822-like:none:notvendor"
    "apt-pkg-native:apt-pkg-native:patches:notvendor"
    "termcolor:termcolor:none:notvendor"
    "curve25519-dalek-derive:curve25519-dalek-derive:none:notvendor"
    "fiat-crypto:fiat-crypto:none:notvendor"
    "addchain:addchain:patches:notvendor"
    "ff-derive:ff_derive:patches:notvendor"
    "ff:ff:none:notvendor"
    "nonempty:nonempty:none:notvendor"
    "memuse:memuse:patches:notvendor"
    "rand-chacha-0.3:rand_chacha 0.3:none:notvendor"
    "packed-simd:packed_simd:patches:vendor"
    "libm-0.1:libm 0.1:none:vendor"
    "packed-simd-2:packed_simd_2:none:vendor"
    "rand-0.8:rand 0.8:none:notvendor"
    "rand-xorshift-0.3:rand_xorshift 0.3:none:notvendor"
    "group:group:none:notvendor"
    "curve25519-dalek:curve25519-dalek:none:notvendor"
    "pkcs8:pkcs8:none:vendor"
    "signature-derive:signature_derive:none:notvendor"
    "signature:signature:none:notvendor"
    "flagset:flagset:none:notvendor"
    "der-0.7:der 0.7:none:vendor"
    "spki:spki:none:notvendor"
    "sha2-asm:sha2-asm:patches:notvendor"
    "sha2-0.10:sha2 0.10:none:notvendor"
    "spki-0.7:spki 0.7:none:vendor"
    "const-oid-0.9:const-oid 0.9:none:notvendor"
    "ed25519:ed25519:none:notvendor"
    "keccak-0.1:keccak 0.1:none:notvendor"
    "merlin:merlin:patches:notvendor"
    "ed25519-dalek:ed25519-dalek:none:notvendor"
    "async-trait:async-trait:none:notvendor"
    "iso8601:iso8601:none:notvendor"
    "md5:md5:none:notvendor"
    "xml-rs:xml-rs:none:notvendor"
    "serde-xml-rs:serde-xml-rs:none:notvendor"
    "any-all-workaround:any_all_workaround:none:vendor"
    "encoding-rs:encoding_rs:none:notvendor"
    "quick-xml:quick-xml:none:notvendor"
    "lber:lber:patches:notvendor"
    "tokio-native-tls:tokio-native-tls:patches:notvendor"
    "ldap3:ldap3:none:vendor"
    "email-address:email_address:none:notvendor"
    "email-encoding:email-encoding:none:notvendor"
    "hostname:hostname:none:notvendor"
    "mime:mime:none:vendor"
    "nom-8:nom 8.0:none:notvendor"
    "quoted-printable:quoted_printable:none:notvendor"
    "concurrent-queue:concurrent-queue:patches:notvendor"
    "generator:generator:none:vendor"
    "scoped-tls:scoped-tls:none:notvendor"
    "windows-result:windows-result:none:vendor"
    "loom:loom:none:vendor"
    "parking:parking:none:notvendor"
    "concurrent-queue:concurrent-queue:none:notvendor"
    "event-listener:event-listener:none:notvendor"
    "event-listener-strategy:event-listener-strategy:none:notvendor"
    "async-channel:async-channel:none:notvendor"
    "event-listener-2:event-listener 2.5:none:notvendor"
    "async-channel-1:async-channel 1.9:none:notvendor"
    "async-task:async-task:none:notvendor"
    "futures-lite:futures-lite:none:notvendor"
    "async-executor:async-executor:none:notvendor"
    "hermit-abi:hermit-abi:none:vendor"
    "polling:polling:none:vendor"
    "async-io:async-io:none:vendor"
    "async-lock:async-lock:none:notvendor"
    "atomic-waker:atomic-waker:none:notvendor"
    "piper:piper:none:notvendor"
    "blocking:blocking:none:notvendor"
    "gloo-timers:gloo-timers:none:notvendor"
    "gloo-timers-0.3:gloo-timers 0.3:none:notvendor"
    "async-global-executor:async-global-executor:patches:vendor"
    "kv-log-macro:kv-log-macro:none:notvendor"
    "wasm-bindgen-futures:wasm-bindgen-futures:none:vendor"
    "async-std:async-std:patches:vendor"
    "boring:boring:none:vendor"
    "futures-rustls:futures-rustls:none:vendor"
    "num-iter:num-iter:none:notvendor"
    "num-bigint-dig:num-bigint-dig:none:notvendor"
    "pkcs1:pkcs1:none:notvendor"
    "rsa:rsa:none:vendor"
    "fslock:fslock:none:notvendor"
    "boring-sys:boring-sys:patches:vendor"
    "bitflags-2:bitflags 2.9:none:notvendor"
    "foreign-types-shared-0.3:foreign-types-shared 0.3:none:notvendor"
    "foreign-types-0.5:foreign-types 0.5:none:notvendor"
    "tokio-boring:tokio-boring:none:notvendor"
    "lettre:lettre:patches:notvendor"
    "hashify:hashify:none:notvendor"
    "mail-parser:mail-parser:none:vendor"
    "getset:getset:none:notvendor"
    "strum:strum:none:vendor"
    "strum-macros:strum_macros:none:vendor"
    "quickcheck:quickcheck:none:vendor"
    "oci-spec:oci-spec:none:notvendor"
    "openidconnect:openidconnect:none:vendor"
    "base64-0.21:base64 0.21:none:vendor"
    "hmac:hmac:none:notvendor"
    "itertools-0.10:itertools 0.10:none:notvendor"
    "rustls-native-certs:rustls-native-certs:none:notvendor"
    "tokio-rustls:tokio-rustls:none:vendor"
    "hyper-rustls:hyper-rustls:none:vendor"
    "hyper-tls:hyper-tls:none:notvendor"
    "system-configuration:system-configuration:none:vendor"
    "tower-layer:tower-layer:patches:notvendor"
    "hyper-util:hyper-util:none:vendor"
    "serde-urlencoded:serde_urlencoded:none:notvendor"
    "hdrhistogram:hdrhistogram:none:notvendor"
    "tower:tower:none:notvendor"
    "compression-core:compression-core:none:notvendor"
    "compression-codecs:compression-codecs:none:vendor"
    "async-compression:async-compression:none:notvendor"
    "http-range-header:http-range-header:none:notvendor"
    "iri-string:iri-string:none:notvendor"
    "mime-guess:mime_guess:patches:notvendor"
    "alloc-no-stdlib:alloc-no-stdlib:patches:notvendor"
    "alloc-stdlib:alloc-stdlib:patches:notvendor"
    "brotli-decompressor:brotli-decompressor:none:vendor"
    "brotli:brotli:patches:vendor"
    "tower-http:tower-http:none:notvendor"
    "web-sys:web-sys:none:notvendor"
    "siphasher-1:siphasher 1:none:notvendor"
    "fastbloom:fastbloom:none:notvendor"
    "lru-slab:lru-slab:none:notvendor"
    "ring:ring:patches:vendor"
    "rustls-webpki:rustls-webpki:none:notvendor"
    "rustls:rustls:patches_2:notvendor"
    "humantime:humantime:none:notvendor"
    "qlog:qlog:patches:notvendor"
    "combine:combine:patches:notvendor"
    "simdutf8:simdutf8:none:notvendor"
    "simd-cesu8:simd_cesu8:none:notvendor"
    "jni-macros:jni-macros:none:notvendor"
    "jni-sys-macros:jni-sys-macros:none:notvendor"
    "jni-sys:jni-sys:none:notvendor"
    "docopt:docopt:patches:notvendor"
    "java-locator:java-locator:none:notvendor"
    "libloading-0.8:libloading 0.8:none:notvendor"
    "jni:jni:none:notvendor"
    "webpki-root-certs:webpki-root-certs:none:notvendor"
    "rustls-platform-verifier:rustls-platform-verifier:patches:vendor"
    "quinn-proto:quinn-proto:patches:notvendor"
    "quinn-udp:quinn-udp:none:vendor"
    "quinn:quinn:none:vendor"
    "reqwest:reqwest:none:vendor"
    "serde-path-to-error:serde_path_to_error:none:notvendor"
    "webpki-roots:webpki-roots:none:notvendor"
    "oauth2:oauth2:patches:notvendor"
    "base16ct:base16ct:none:notvendor"
    "rustc-hex:rustc-hex:patches:notvendor"
    "rlp-derive:rlp-derive:patches:notvendor"
    "rlp:rlp:patches:notvendor"
    "serdect:serdect:patches:notvendor"
    "crypto-bigint:crypto-bigint:none:notvendor"
    "hkdf:hkdf:patches:notvendor"
    "hex-literal:hex-literal:none:notvendor"
    "pem-rfc7468-0.7:pem-rfc7468 0.7:none:notvendor"
    "sec1:sec1:none:notvendor"
    "elliptic-curve:elliptic-curve:patches:notvendor"
    "rfc6979:rfc6979:patches:notvendor"
    "ecdsa:ecdsa:patches:notvendor"
    "primeorder:primeorder:none:notvendor"
    "p256:p256:none:notvendor"
    "hex-literal-0.3:hex-literal 0.3:none:notvendor"
    "p384:p384:none:notvendor"
    "ordered-float:ordered-float:patches:notvendor"
    "serde-value:serde-value:patches:notvendor"
    "temp-dir:temp-dir:none:vendor"
    "gettext-sys:gettext-sys:none:vendor"
    "locale-config:locale_config:patches:notvendor"
    "gettext-rs:gettext-rs:none:vendor"
    "gettext:gettext:none:vendor"
    "tr:tr:patches:notvendor"
    "xtr:xtr:none:notvendor"
    "ascii:ascii:none:vendor"
    "encode-unicode:encode_unicode:none:notvendor"
    "prettytable-rs:prettytable-rs:none:vendor"
    "x25519-dalek:x25519-dalek:none:notvendor"
    "libudev-sys:libudev-sys:none:notvendor"
    "io-lifetimes:io-lifetimes:patches:notvendor"
    "udev:udev:patches:notvendor"
    "openssl-probe-0.1:openssl-probe 0.1:patches:notvendor"
    "nvml-sys:nvml-sys:patches:vendor"
    "bitflags-1:bitflags 1:patches:notvendor"
    "quick-error-1:quick-error 1:patches:notvendor"
    "errno-dragonfly:errno-dragonfly:patches:notvendor"
    "errno-0.2:errno 0.2:patches:notvendor"
    "rust-extra:rust-extra:none:vendor"
    "serde-repr:serde_repr:none:notvendor"
    "syscalls:syscalls:none:notvendor"
    "nvml:nvml:patches:vendor"
    "nvml-wrapper:nvml-wrapper:none:notvendor"
  )

export CARGO=/usr/local/bin/cargo
export RUSTC=/usr/local/bin/rustc

rm .git &&
git init
git config --global --add safe.directory $(pwd)

# Update repos so rust can install dependencie libraries
apt update;
apt update;

build_rust_libs(){
  rust_lib=$1
  repackage_name=$2
  patch_name=$3
  vendor=$4

  rm -rf ./build/*
  # Prepare patch for ./repackage.sh script
  cp -r "./src/${rust_lib}/" "/tmp/tmp_${rust_lib}"
  if [[ $patch_name == "none" ]]; then
    rm -rf "./src/${rust_lib}/debian/patches/"
    rm -rf "./src/${rust_lib}/debian/patches_*/"
    ./repackage.sh ${repackage_name}
  elif [[ $patch_name == "patches" ]]; then
    rm -rf "./src/${rust_lib}/debian/patches_*/"
    ./repackage.sh ${repackage_name}
  else
    rm -rf "./src/${rust_lib}/debian/patches/"
    mv "./src/${rust_lib}/debian/${patch_name}/" "./src/${rust_lib}/debian/patches"
    rm -rf "./src/${rust_lib}/debian/patches_*/"
    ./repackage.sh ${repackage_name}
  fi
  rm -rf "./src/${rust_lib}/"
  mv "/tmp/tmp_${rust_lib}" "./src/${rust_lib}"
  # Build librust package
  (
    cd ./build/${rust_lib}/;
    if [[ $vendor == "notvendor" ]]; then
      yes |mk-build-deps --install --remove; \
      dpkg-buildpackage -b -us -uc
    elif [[ $vendor == "vendor" ]]; then
      $CARGO vendor && \
      # Remove windows crates \
      rm -rf ./vendor/windows*; \
      rm -rf ./vendor/vcpkg/test-data/normalized/installed/*; \
      # Remove controls depends section because it's not needed for vendor
      DEBIAN_CONTROL_FILE="./debian/control"
      awk '/^Depends:/{skip=1; next} skip && /^[[:space:]]/{next} {skip=0; print}' "$DEBIAN_CONTROL_FILE" > "$DEBIAN_CONTROL_FILE.tmp"
      mv "$DEBIAN_CONTROL_FILE.tmp" "$DEBIAN_CONTROL_FILE"
      DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" dpkg-buildpackage -b -us -uc -Pnocheck
    fi
  )
  mkdir -p /tmp/${PKGNAME}-temp
  mkdir -p ./deb/
  for deb_pkg in $(find $(pwd)/build/ -name "*.deb"); do
    cp ${deb_pkg} "/tmp/${PKGNAME}-temp/"
    cp ${deb_pkg} "./deb/"
  done
  apt install --reinstall -y --allow-downgrades /tmp/${PKGNAME}-temp/*.deb || return $? &&
  rm -rf /tmp/${PKGNAME}-temp

  echo "Build finished for rust library ${repackage_name}..."
}

TOTAL=${#RUST_LIBS[@]}
CURRENT=0
for entry in "${RUST_LIBS[@]}"; do
  IFS=':' read -r \
    rust_lib \
    repackage_name \
    patch_name \
    vendor \
    <<< "$entry"
  CURRENT=$((CURRENT + 1))
  print_progress ${TOTAL} ${CURRENT} "${repackage_name}"
  if [ ! -t 1 ]; then
    log_file=$(mktemp)
    if ! build_rust_libs "${rust_lib}" "${repackage_name}" "${patch_name}" "${vendor}" > "$log_file" 2>&1; then
      echo "ERROR: build_rust_libs failed for ${rust_lib}" >&2
      cat "$log_file" >&2
      rm -f "$log_file"
      exit 1
    fi
    rm -f "$log_file"
  else
    if ! build_rust_libs "${rust_lib}" "${repackage_name}" "${patch_name}" "${vendor}"; then
      echo "ERROR: build_rust_libs failed for ${rust_lib}" >&2
      exit 1
    fi
  fi
done

